name: ch7_animation_controller
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drop_shadow_image: ^0.9.1
  animated_background: ^2.0.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
